### ISSUE TITLE
MVP 2: User auth

### ISSUE THREAD

**Issue by ahamacher** [ahamacher/Flack#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

**Comment by ronilbhatia** [comment]
Really good job with the styling! The site is almost identical to Slack's. This issue is close to being closed out but there are a few things that we need to fix:

1. After I log in if I visit a random route, I get redirected to the splash page, which gives me links to sign-in/sign-up. This isn't the best since I am already signed in. There's a couple of ways you could get around this, but probably the easiest to keep your routes the way you currently have them, is to add a `componentDidMount` to your splash page where you check if there is a current user logged in, and if there is, you do a `this.props.history.push("/channel")`. The alternative is to have your `/channel` route just be your `/` route instead, and have the component rendered by this route do a ternary based on whether there is a current user logged in - if there is render the `Channel` component, otherwise render the `Splash` component. Let me know if this is unclear, or you are unsure how to proceed here.
2. Errors are not clearing between `signup` and `login` - in order to get them to add a `componentWillUnmount` to your `SessionForm` component and invoke the `clearErrors` action you should have written.
3. Right now the 'logout' and 'demo login' buttons do not have cursor pointer on them. Also your demo login is pretty easy to miss - I would style it in a similar manner to the big 'Continue -->' button you have on your session form. I would even add a link to it somewhere in your Splash page. We want to make it as easy as possible for recruiters to be able to do a demo login.
4. When errors are rendered your input boxes move down the page, which is not ideal. To get around this, create a container for the errors, of a fixed height and width. That way when there is an error it will already have allocated space to render under, instead of needing to push other elements down.

**Comment by ahamacher** [comment]
Thank you for the review! I have fixed these issues:

1. Redirect automatically to the `"/channel"` page if logged in and gibberish is sent as a route. redirect to the `"/"` if not logged in. 
2. errors now clear upon refreshing. used `componentWillUnmount` and passed in a `clearSessionErrors` action.
3. Fixed hover over for the demo and logout buttons. Added a demo login to the splash header and added an or to the one on the login page. I hope this is an alright solution since I didn't really want to have another huge green button for the demo user.
4. fixed the location of the errors box and its padding/margin. It no longer moves the boxes down.
